package com.example.dynamodbcrud.api.model;



import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Data
@Getter
@Setter
@DynamoDBTable(tableName = "book")
public class Book {

	/*
	 * public String getId() { return id; } public void setId(String id) { this.id =
	 * id; } public String getName() { return name; } public void setName(String
	 * name) { this.name = name; } public String getIsbn() { return isbn; } public
	 * void setIsbn(String isbn) { this.isbn = isbn; } public String getAuthorId() {
	 * return authorId; } public void setAuthorId(String authorId) { this.authorId =
	 * authorId; }
	 */
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String isbn;
    @DynamoDBAttribute
    private String authorId;
	

}