package com.example.dynamodbcrud.api.model;



import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "lend")
public class Lend {

	/*
	 * public String getId() { return id; }
	 * 
	 * public void setId(String id) { this.id = id; }
	 * 
	 * public LendStatus getStatus() { return status; }
	 * 
	 * public void setStatus(LendStatus status) { this.status = status; }
	 * 
	 * public String getStartOn() { return startOn; }
	 * 
	 * public void setStartOn(String startOn) { this.startOn = startOn; }
	 * 
	 * public String getDueOn() { return dueOn; }
	 * 
	 * public void setDueOn(String dueOn) { this.dueOn = dueOn; }
	 * 
	 * public String getBookId() { return bookId; }
	 * 
	 * public void setBookId(String bookId) { this.bookId = bookId; }
	 * 
	 * public String getMemberId() { return memberId; }
	 * 
	 * public void setMemberId(String memberId) { this.memberId = memberId; }
	 */

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private LendStatus status;

    @DynamoDBAttribute
    private String startOn;

    @DynamoDBAttribute
    private String dueOn;
    
    @DynamoDBAttribute
    private String bookId;

    @DynamoDBAttribute
    private String memberId;


}